SHEET_NAME_NETWORK = 'network'
COL_NAME_NAME = 'name'
COL_NAME_FREQUENCY = 'f_hz'
COL_NAME_REF_POWER = 'sn_mva'

SHEET_NAME_NODES = 'nodes'
COL_NAME_INDEX = 'index'
COL_NAME_VOLTAGE = 'vn_kv'
COL_NAME_LONGITUDE = 'longitude'
COL_NAME_LATITUDE = 'latitude'
COL_NAME_ZONE = 'zone'
COL_NAME_MAX_VOLTAGE = 'max_vm_pu'
COL_NAME_MIN_VOLTAGE = 'min_vm_pu'
COL_NAME_SERVICE = 'in_service'
COL_NAME_FRAGILITY_CURVE = 'fragility_curve'
COL_NAME_KF = 'kf'
COL_NAME_RESILIENCE_FULL = 'resilienceFull'
COL_NAME_WEATHER_TTR = 'weatherTTR'

SHEET_NAME_TRANSFORMER = 'transformers'
COL_NAME_NODE_P = 'node_p'
COL_NAME_NODE_S = 'node_s'
COL_NAME_PARALLEL = 'parallel'
COL_NAME_TAP_POS = 'tap_pos'
COL_NAME_VECTOR_GROUP = 'vector_group'
COL_NAME_MAX_LOADING = 'max_loading_percent'
COL_NAME_DF = 'df'
COL_NAME_TYPE = 'type'

SHEET_NAME_TR_TYPE = 'tr_type'
COL_NAME_VN_HV = 'vn_hv_kv'
COL_NAME_VN_LV = 'vn_lv_kv'
COL_NAME_VK = 'vk_percent'
COL_NAME_VKR = 'vkr_percent'
COL_NAME_PFE = 'pfe_kw'
COL_NAME_I0 = 'i0_percent'
COL_NAME_SHIFT = 'shift_degree'
COL_NAME_TAP_SIDE = 'tap_side'
COL_NAME_TAP_NEUTRAL = 'tap_neutral'
COL_NAME_TAP_MIN = 'tap_min'
COL_NAME_TAP_MAX = 'tap_max'
COL_NAME_TAP_STEP = 'tap_step_percent'
COL_NAME_TAP_STEP_ANGLE = 'tap_step_degree'
COL_NAME_TAP_PHASE_SHIFTER = 'tap_phase_shifter'

SHEET_NAME_LINES = 'lines'
COL_NAME_FROM_BUS = 'from_bus'
COL_NAME_TO_BUS = 'to_bus'
COL_NAME_LENGTH = 'length_km'
COL_NAME_FROM_LONGITUDE = 'from_longitude'
COL_NAME_FROM_LATITUDE = 'from_latitude'
COL_NAME_TO_LONGITUDE = 'to_longitude'
COL_NAME_TO_LATITUDE = 'to_latitude'

SHEET_NAME_LN_TYPE = 'ln_type'
COL_NAME_R1 = 'r_ohm_per_km'
COL_NAME_X1 = 'x_ohm_per_km'
COL_NAME_C1 = 'c_nf_per_km'
COL_NAME_R0 = 'r0_ohm_per_km'
COL_NAME_X0 = 'x0_ohm_per_km'
COL_NAME_C0 = 'c0_nf_per_km'
COL_NAME_MAX_I = 'max_i_ka'
COL_NAME_G1 = 'g_us_per_km'
COL_NAME_G0 = 'g0_us_per_km'

SHEET_NAME_LOADS = 'loads'
COL_NAME_BUS = 'node'
COL_NAME_P = 'p_mw'
COL_NAME_Q = 'q_mvar'
COL_NAME_CONST_Z = 'const_z_percent'
COL_NAME_CONST_I = 'const_i_percent'
COL_NAME_SCALING = 'scaling'
COL_NAME_MAX_P = 'max_p_mw'
COL_NAME_MIN_P = 'min_p_mw'
COL_NAME_MAX_Q = 'max_q_mvar'
COL_NAME_MIN_Q = 'min_q_mvar'
COL_NAME_CONTROLLABLE = 'controllable'

SHEET_NAME_EXTERNAL_GEN = 'external_gen'
COL_NAME_VM = 'vm_pu'
COL_NAME_VA = 'va_degree'
COL_NAME_MAX_S_SC = 's_sc_max_mva'
COL_NAME_MIN_S_SC = 's_sc_min_mva'
COL_NAME_MAX_RX = 'rx_max'
COL_NAME_MIN_RX = 'rx_min'
COL_NAME_MAX_R0X0 = 'r0x0_max'
COL_NAME_MAX_X0X = 'x0x_max'
COL_NAME_SLACK_WEIGHT = 'slack_weight'

SHEET_NAME_SGEN = 'static_generators'
COL_NAME_CS = 'current_source'

SHEET_NAME_GENERATORS = 'generators'
COL_NAME_LACK = 'lack'
COL_NAME_XDSS = 'xdss_pu'
COL_NAME_RDSS = 'rdss_ohm'
COL_NAME_COS_PHI = 'cos_phi'
COL_NAME_PG = 'pg_percent'
COL_NAME_PS_TRAFO = 'power_station_trafo'
COL_NAME_SLACK = 'slack'

SHEET_NAME_COST = 'cost'
COL_NAME_CP1 = 'cp1_eur_per_mw'
COL_NAME_CP0 = 'cp0_eur'
COL_NAME_CQ1 = 'cq1_eur_per_mvar'
COL_NAME_CQ0 = 'cq0_eur'
COL_NAME_CP2 = 'cp2_eur_per_mw2'
COL_NAME_CQ2 = 'cq2_eur_per_mvar2'

SHEET_NAME_PROFILES = 'profiles'
SHEET_NAME_CREWS = 'crews'
SHEET_NAME_SIMULATION = 'simulation'

COL_NAME_FIELD = 'field'
COL_NAME_VALUE = 'value'
COL_NAME_UNIT = 'unit'

SHEET_NAME_SWITCHES = 'switches'
COL_NAME_ELEMENT = 'element'
COL_NAME_ET = 'et'
COL_NAME_CLOSED = 'closed'
# COL_NAME_I_CLOSED = 'initial_closed'
COL_NAME_IN_KA = 'in_ka'

# COL_NAME_DISCONECTING_ELEMENTS = 'disconnecting_elements'